######################################################################
# Automatically generated by qmake (2.01a) Fri 14. Jun 15:30:24 2013
######################################################################

TEMPLATE = app
TARGET = cppn-x
DEPENDPATH += . cppn-x/include cppn-x/src JGTL/include
INCLUDEPATH += .
INCLUDEPATH += cppn-x/include
INCLUDEPATH += JGTL/include
INCLUDEPATH += D:/programmas/lib/boost_1_47

# Input
HEADERS += cppn-x/include/CE_ActivationFunctions.h \
           cppn-x/include/CE_ColorButton.h \
           cppn-x/include/CE_Cppn.h \
           cppn-x/include/CE_CppnParser.h \
           cppn-x/include/CE_CppnWidget.h \
           cppn-x/include/CE_CppnWriter.h \
           cppn-x/include/CE_Defines.h \
           cppn-x/include/CE_Edge.h \
           cppn-x/include/CE_FinalNodeView.h \
           cppn-x/include/CE_Node.h \
           cppn-x/include/CE_NodeView.h \
           cppn-x/include/CE_Window.h \
           cppn-x/include/CE_Xml.h \
           JGTL/include/JGTL_Bar.h \
           JGTL/include/JGTL_CircularBuffer.h \
           JGTL/include/JGTL_CircularBufferInterface.h \
           JGTL/include/JGTL_CommandLineParser.h \
           JGTL/include/JGTL_DataManager.h \
           JGTL/include/JGTL_DataPool_delete.h \
           JGTL/include/JGTL_DynamicCircularBuffer.h \
           JGTL/include/JGTL_DynamicPoolMap.h \
           JGTL/include/JGTL_DynamicPoolSet.h \
           JGTL/include/JGTL_FloatingUnits.h \
           JGTL/include/JGTL_HexTree.h \
           JGTL/include/JGTL_Index2.h \
           JGTL/include/JGTL_Index3.h \
           JGTL/include/JGTL_IntegralUnits.h \
           JGTL/include/JGTL_InterpolatedValue.h \
           JGTL/include/JGTL_LocatedException.h \
           JGTL/include/JGTL_MapInterface.h \
           JGTL/include/JGTL_PolyVariant.h \
           JGTL/include/JGTL_PoolMap_delete.h \
           JGTL/include/JGTL_Quadratic.h \
           JGTL/include/JGTL_QuadTree.h \
           JGTL/include/JGTL_QuickProf.h \
           JGTL/include/JGTL_Ray2.h \
           JGTL/include/JGTL_Ray3.h \
           JGTL/include/JGTL_Rectangle3.h \
           JGTL/include/JGTL_Serialization.h \
           JGTL/include/JGTL_SetInterface.h \
           JGTL/include/JGTL_Singleton.h \
           JGTL/include/JGTL_SortedList_delete.h \
           JGTL/include/JGTL_StackCircularBuffer.h \
           JGTL/include/JGTL_StackMap.h \
           JGTL/include/JGTL_StackSet.h \
           JGTL/include/JGTL_StringConverter.h \
           JGTL/include/JGTL_TreeList.h \
           JGTL/include/JGTL_UnorderedDynamicPoolMap.h \
           JGTL/include/JGTL_UnorderedMapInterface.h \
           JGTL/include/JGTL_Variant.h \
           JGTL/include/JGTL_Vector2.h \
           JGTL/include/JGTL_Vector3.h \
           JGTL/include/JGTL_Vector4.h \
           JGTL/include/JGTL_WrappedInterpolatedValue.h \
           JGTL/include/JGTL_XorSpace.h
SOURCES += cppn-x/src/CE_ActivationFunctions.cpp \
           cppn-x/src/CE_ColorButton.cpp \
           cppn-x/src/CE_Cppn.cpp \
           cppn-x/src/CE_CppnParser.cpp \
           cppn-x/src/CE_CppnWidget.cpp \
           cppn-x/src/CE_CppnWriter.cpp \
           cppn-x/src/CE_Edge.cpp \
           cppn-x/src/CE_FinalNodeView.cpp \
           cppn-x/src/CE_Main.cpp \
           cppn-x/src/CE_Node.cpp \
           cppn-x/src/CE_NodeView.cpp \
           cppn-x/src/CE_Window.cpp
